global:
  smtp_smarthost: 'smtp:80'
  smtp_from: 'example@example.com'
  smtp_auth_username: 'username'
  smtp_auth_password: 'password'


route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'example@example.com'
        send_resolved: true