global:
  scrape_interval: 15s # 1 min

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8087']
    scrape_interval: 20s
  - job_name: 'example-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.23.0.2:8092']